name: Build

# Because a PR results in a push; this workflow will run when a PR is merged
# or when a commit is pushed directly to any branch.
on:
  push:
    branches:
      - '*'

jobs:

  vm:
    runs-on: ubuntu-latest

    steps:
      - name: Run on VM
        run: |
          echo This job does not specify a container.
          echo It runs directly on the virtual machine.
          echo $PATH

  container:
    runs-on: ubuntu-latest

    container: espressif/idf

    steps:
      - uses: actions/checkout@v2

      - name: Run in container
        run: |
          echo This job does specify a container.
          echo It runs in the container instead of the VM.
          echo $PATH
